# This is a TOML document.
# For information on TOML documents and how to write them visit
# https://en.wikipedia.org/wiki/TOML
# https://github.com/toml-lang/toml

# App options

local_timezone = 'America/Los_Angeles'

input_path = './input'
app_log_path = './logs'
app_log_filename = 'app.log'
refresh_per_second = 1
main_loop_throttle = 0.1

ip_addresses = [
    '192.168.1.1',
    '192.168.1.3',
    '192.168.1.81',
    '192.168.1.82',
    '192.168.1.83',
    '192.168.1.91',
    '192.168.1.92',
    '192.168.1.93',
    '192.168.1.94',
    '192.168.1.95',
    '192.168.1.96',
    '192.168.1.97',
    '192.168.1.98',
    '192.168.1.99',
    'www.yahoo.com',
    'www.google.com',
    '8.8.8.8',
    '8.8.4.4',
    '192.168.1.104',
    '192.168.1.105',
    '192.168.1.106',
    '192.168.1.107',
    '192.168.1.108',
    '192.168.1.109',
    '192.168.1.110',
    '192.168.1.111',
    '192.168.1.112',
    '192.168.1.113',
    '192.168.1.114',
    '192.168.1.115',
    '192.168.1.116',
    '192.168.1.117',
    '192.168.1.118',
    '192.168.1.119',
    '192.168.1.120',
    '192.168.1.121',
    '192.168.1.122',
    '192.168.1.123',
    '192.168.1.124',
    '192.168.1.125',
    '192.168.1.126'
]

# Logging Options
[loggers]
# Available options:
# level: 'CRITICAL', 'FATAL', 'ERROR', 'WARN', 'WARNING', 'INFO', 'DEBUG'
# format: https://docs.python.org/3/howto/logging.html#formatters
    [loggers.console]
        level = "DEBUG"
        format = '%(levelname)s - %(module)s - %(message)s'

    [loggers.file]
        level = "DEBUG"
        format = "%(asctime)s - %(module)s - %(levelname)s - %(message)s"

    [loggers.rotating_file]
        # second (s), minute (m), hour (h), day (d)
        level = "DEBUG"
        format = "%(asctime)s - %(module)s - %(levelname)s - %(message)s"
        when = "d"
        interval = 1
        backupCount = 14
